[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
solc_version = "0.8.21"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"        

[rpc_endpoints]
anvil    = "${RPC_ANVIL}"
coston2  = "${RPC_COSTON2}"
songbird = "${RPC_SONGBIRD}"
flare    = "${RPC_FLARE}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 256
